par(mfrow=c(3,3),mar=c(2,5,2,1),las=1,bty="n")
plot(airquality$Ozone,type = 'l')
plot(airquality$Ozone,type = 'l')
plot(airquality$Ozone,type = 'l')
hist(airquality$Solar.R)
hist(airquality$Solar.R)
boxplot(airquality$Solar.R)
boxplot(airquality[,0:4],main='multiple box plots')
boxplot(airquality$Solar.R)
boxplot(airquality[,0:4],main='multiple box plots')