install.packages("moments")
library(moments)
mean(airquality$Ozone,na.rm = T)
median(airquality$Ozone,na.rm = T)
var(airquality$Ozone,na.rm = T)
sd(airquality$Ozone,na.rm = T)
skewness(airquality$Ozone,na.rm = T)
kurtosis(airquality$Ozone,na.rm = T)
skewness(airquality,na.rm = T)
